{{- if .Values.rbac.setup -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prepull.name" . }}-sa
  annotations:
    "helm.sh/hook": pre-install
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "prepull.name" . }}-cr
  annotations:
    "helm.sh/hook": pre-install
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch","delete"]
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["get", "list", "watch","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "prepull.name" . }}-crb
  annotations:
    "helm.sh/hook": pre-install
subjects:
- kind: ServiceAccount
  name: {{ include "prepull.name" . }}-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole 
  name: {{ include "prepull.name" . }}-cr
  apiGroup: rbac.authorization.k8s.io
{{- end }}